# Generated by Django 5.0.1 on 2024-02-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autos_disponibles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_auto', models.CharField(max_length=50)),
                ('nombre_primer_dueño', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('modelo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='metodo_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efectivo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='permutacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_auto', models.CharField(max_length=50)),
                ('nombre_primer_dueño', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('modelo', models.IntegerField()),
            ],
        ),
    ]
