# Generated by Django 5.0.1 on 2024-02-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodo_pago',
            name='efectivo',
            field=models.CharField(max_length=50),
        ),
    ]
