# Generated by Django 5.0.1 on 2024-02-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos_disponibles',
            name='imagen',
            field=models.ImageField(null=True, upload_to='avatares'),
        ),
    ]
