# Generated by Django 5.0.1 on 2024-02-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0006_alter_autos_disponibles_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='agencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agencia', models.CharField(max_length=50)),
                ('nombre_dueño', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
        migrations.AddField(
            model_name='permutacion',
            name='imagenes',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
