# Generated by Django 5.0.1 on 2024-02-23 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_agencias_permutacion_imagenes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='agencias',
            new_name='agenciass',
        ),
        migrations.RenameField(
            model_name='agenciass',
            old_name='direccion',
            new_name='direccionn',
        ),
        migrations.RenameField(
            model_name='agenciass',
            old_name='imagen',
            new_name='imagenn',
        ),
        migrations.RenameField(
            model_name='agenciass',
            old_name='nombre_agencia',
            new_name='nombre_agenciass',
        ),
        migrations.RenameField(
            model_name='agenciass',
            old_name='nombre_dueño',
            new_name='nombre_dueñoo',
        ),
    ]
