# Generated by Django 5.0.1 on 2024-02-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0009_rename_direccionn_agenciass_agencias_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenciass',
            old_name='dueño',
            new_name='dueno',
        ),
    ]
