# Generated by Django 5.0.1 on 2024-02-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0010_rename_dueño_agenciass_dueno'),
    ]

    operations = [
        migrations.CreateModel(
            name='agencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_agencias', models.CharField(max_length=50)),
                ('nombre_dueño', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('imagenes', models.ImageField(blank=True, null=True, upload_to='avatares')),
            ],
        ),
        migrations.DeleteModel(
            name='agenciass',
        ),
    ]
