# Generated by Django 5.0.1 on 2024-02-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_agencias_delete_agenciass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencias',
            old_name='imagenes',
            new_name='image',
        ),
    ]
