# Generated by Django 5.0.1 on 2024-02-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_rename_nombre_auto_permutacion_nombre_autoo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permutacion',
            old_name='nombre_autoo',
            new_name='nombre_auto',
        ),
    ]
